services:

  dbserver:
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    image: biarms/mysql:5.5.62
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - "./data/mysql/data:/var/lib/mysql:Z"
      - "./data/mysql/initdb:/docker-entrypoint-initdb.d:Z"

  openssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      PUBLIC_KEY_DIR: ./data/openssh/trusted_public_keys 
      USER_NAME: ${SSH_REMOTEUSER}
    volumes:
      - "./data/openssh/config:/config:Z"
    ports:
      - "2222:2222"
    restart: unless-stopped
